import feedparser
import json
import os
import requests
from urllib.parse import urlparse

def main():
    # Define the cache directory relative to the script location
    CACHE_DIR = "assets/media_cache"
    if not os.path.exists(CACHE_DIR):
        os.makedirs(CACHE_DIR)

    rss_url = "https://infosec.exchange/@sounddrill/tagged/sidekick.rss"
    feed = feedparser.parse(rss_url)
    
    posts = []
    for entry in feed.entries:
        media_content = []
        if hasattr(entry, 'media_content'):
            for media in entry.media_content:
                media_url = media.get('url')
                if not media_url:
                    continue

                # Define the size limit (10MB)
                MAX_SIZE = 10 * 1024 * 1024
                
                try:
                    # Use a HEAD request to check the content length
                    head_response = requests.head(media_url, allow_redirects=True, timeout=10)
                    head_response.raise_for_status()
                    size = int(head_response.headers.get('content-length', 0))

                    # Generate a local filename from the URL
                    parsed_url = urlparse(media_url)
                    filename = os.path.basename(parsed_url.path)
                    if not filename:
                        filename = str(hash(media_url)) + '.' + media.get('type', 'image/jpeg').split('/')[1]
                    
                    local_path = os.path.join(CACHE_DIR, filename)
                    
                    media_path_to_use = media_url # Default to original URL

                    # Download only if the file is within the size limit
                    if size > 0 and size <= MAX_SIZE:
                        if not os.path.exists(local_path):
                            print(f"File size {size / 1024 / 1024:.2f}MB. Downloading {media_url} to {local_path}...")
                            response = requests.get(media_url, stream=True, timeout=30)
                            response.raise_for_status()
                            with open(local_path, 'wb') as f:
                                for chunk in response.iter_content(chunk_size=8192):
                                    f.write(chunk)
                        else:
                            print(f"Skipping existing file: {local_path}")
                        media_path_to_use = local_path # Use local path for smaller files
                    elif size > MAX_SIZE:
                        print(f"File size {size / 1024 / 1024:.2f}MB is over the limit. Streaming from {media_url}")
                    else:
                        print(f"Could not determine file size for {media_url}. Streaming from origin.")

                except requests.exceptions.RequestException as e:
                    print(f"Error processing {media_url}: {e}")
                    continue # Skip this media item if there's an error
                except Exception as e:
                    print(f"An unexpected error occurred with {media_url}: {e}")
                    continue

                media_item = {
                    'url': media_path_to_use, # Use the determined path
                    'type': media.get('type'),
                    'medium': media.get('medium')
                }
                if 'description' in media and media['description'] and media['description'][0].get('value'):
                     media_item['description'] = media['description'][0].get('value')
                media_content.append(media_item)

        posts.append({
            "link": entry.link,
            "pubDate": entry.published,
            "description": entry.summary,
            "media_content": media_content
        })

    output_file = "links-autogenerated.json"
    with open(output_file, "w") as f:
        json.dump(posts, f, indent=4)
    print(f"Successfully fetched and saved {len(posts)} posts to {output_file}")

if __name__ == "__main__":
    main()
