import feedparser
import json
import os

def main():
    rss_url = "https://infosec.exchange/@sounddrill/tagged/sidekick.rss"
    feed = feedparser.parse(rss_url)
    
    posts = []
    for entry in feed.entries:
        media_content = []
        if hasattr(entry, 'media_content'):
            for media in entry.media_content:
                media_item = {
                    'url': media.get('url'),
                    'type': media.get('type'),
                    'medium': media.get('medium')
                }
                if 'description' in media and media['description'] and media['description'][0].get('value'):
                     media_item['description'] = media['description'][0].get('value')
                media_content.append(media_item)

        posts.append({
            "link": entry.link,
            "pubDate": entry.published,
            "description": entry.summary,
            "media_content": media_content
        })

    output_file = "links-autogenerated.json"
    with open(output_file, "w") as f:
        json.dump(posts, f, indent=4)
    print(f"Successfully fetched and saved {len(posts)} posts to {output_file}")

if __name__ == "__main__":
    main()
